//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 



package com.strukturartgsnaloga;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.strukturartgsnaloga package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.strukturartgsnaloga
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStrukturaRtgsNalogaResponse }
     * 
     */
    public GetStrukturaRtgsNalogaResponse createGetStrukturaRtgsNalogaResponse() {
        return new GetStrukturaRtgsNalogaResponse();
    }

    /**
     * Create an instance of {@link Mt900 }
     * 
     */
    public Mt900 createMt900() {
        return new Mt900();
    }

    /**
     * Create an instance of {@link GetMt910Response }
     * 
     */
    public GetMt910Response createGetMt910Response() {
        return new GetMt910Response();
    }

    /**
     * Create an instance of {@link Mt910 }
     * 
     */
    public Mt910 createMt910() {
        return new Mt910();
    }

    /**
     * Create an instance of {@link GetStrukturaRtgsNalogaRequest }
     * 
     */
    public GetStrukturaRtgsNalogaRequest createGetStrukturaRtgsNalogaRequest() {
        return new GetStrukturaRtgsNalogaRequest();
    }

    /**
     * Create an instance of {@link StrukturaRtgsNaloga }
     * 
     */
    public StrukturaRtgsNaloga createStrukturaRtgsNaloga() {
        return new StrukturaRtgsNaloga();
    }

    /**
     * Create an instance of {@link GetMt910Request }
     * 
     */
    public GetMt910Request createGetMt910Request() {
        return new GetMt910Request();
    }

}
