//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 



package com.example.bankxml.bankxml.mt102;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.bankxml.bankxml.mt102 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.bankxml.bankxml.mt102
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMt910RequestMt102 }
     * 
     */
    public GetMt910RequestMt102 createGetMt910RequestMt102() {
        return new GetMt910RequestMt102();
    }

    /**
     * Create an instance of {@link Mt910 }
     * 
     */
    public Mt910 createMt910() {
        return new Mt910();
    }

    /**
     * Create an instance of {@link Mt102 }
     * 
     */
    public Mt102 createMt102() {
        return new Mt102();
    }

    /**
     * Create an instance of {@link GetMt102Response }
     * 
     */
    public GetMt102Response createGetMt102Response() {
        return new GetMt102Response();
    }

    /**
     * Create an instance of {@link Mt900 }
     * 
     */
    public Mt900 createMt900() {
        return new Mt900();
    }

    /**
     * Create an instance of {@link GetMt102Request }
     * 
     */
    public GetMt102Request createGetMt102Request() {
        return new GetMt102Request();
    }

    /**
     * Create an instance of {@link GetMt910Response }
     * 
     */
    public GetMt910Response createGetMt910Response() {
        return new GetMt910Response();
    }

    /**
     * Create an instance of {@link NalogZaMT102 }
     * 
     */
    public NalogZaMT102 createNalogZaMT102() {
        return new NalogZaMT102();
    }

}
